#pragma once

#define LOCAL_RUS
//#define LOCAL_ENG


#ifdef LOCAL_RUS

#define LOCAL_LOG_CONTROL_UP_BUTTON_NAME "Вверх"
#define LOCAL_LOG_CONTROL_DOWN_BUTTON_NAME "Вниз"
#define LOCAL_LOG_CONTROL_LAST_BUTTON_NAME "Последнее"

#define LOCAL_USO_MODE_CONTROL_MODE_FULL_AUTO_TEXT "Автоматический"
#define LOCAL_USO_MODE_CONTROL_MODE_HALF_AUTO_TEXT "Полуавтоматический"
#define LOCAL_USO_MODE_CONTROL_MODE_TOOLS_TEXT "Управление"
#define LOCAL_USO_MODE_CONTROL_USO_MODE_SET_MESSAGE_FULL_AUTO "Выбран автоматический режим работы"
#define LOCAL_USO_MODE_CONTROL_USO_MODE_SET_MESSAGE_HALF_AUTO "Выбран полуавтоматический режим работы"
#define LOCAL_USO_MODE_CONTROL_USO_MODE_SET_MESSAGE_TOOLS "Выбран режим настройки"

#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER "rdefaultProcessorInterruptHandler"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER0 "rdefaultProcessorInterruptHandler0"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER1 "rdefaultProcessorInterruptHandler1"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER2 "rdefaultProcessorInterruptHandler2"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER3 "rdefaultProcessorInterruptHandler3"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER4 "rdefaultProcessorInterruptHandler4"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER5 "rdefaultProcessorInterruptHandler5"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER6 "rdefaultProcessorInterruptHandler6"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER7 "rdefaultProcessorInterruptHandler7"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER8 "rdefaultProcessorInterruptHandler8"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER9 "rdefaultProcessorInterruptHandler9"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER10 "rdefaultProcessorInterruptHandler10"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER11 "rdefaultProcessorInterruptHandler11"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER12 "rdefaultProcessorInterruptHandler12"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER13 "rdefaultProcessorInterruptHandler13"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER14 "rdefaultProcessorInterruptHandler14"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER15 "rdefaultProcessorInterruptHandler15"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER16 "rdefaultProcessorInterruptHandler16"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER17 "rdefaultProcessorInterruptHandler17"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER18 "rdefaultProcessorInterruptHandler18"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER19 "rdefaultProcessorInterruptHandler19"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER20 "rdefaultProcessorInterruptHandler20"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER21 "rdefaultProcessorInterruptHandler21"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER22 "rdefaultProcessorInterruptHandler22"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER23 "rdefaultProcessorInterruptHandler23"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER24 "rdefaultProcessorInterruptHandler24"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER25 "rdefaultProcessorInterruptHandler25"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER26 "rdefaultProcessorInterruptHandler26"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER27 "rdefaultProcessorInterruptHandler27"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER28 "rdefaultProcessorInterruptHandler28"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER29 "rdefaultProcessorInterruptHandler29"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER30 "rdefaultProcessorInterruptHandler30"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER31 "rdefaultProcessorInterruptHandler31"

#define LOCAL_LOG_LOG_CREATE_MESSAGE "Создан новый журнал"

#define LOCAL_TOOLS_TAB_CONTROL_EXIT_BUTTON_TEXT "Выход"
#define LOCAL_TOOLS_TAB_CONTROL_UPDATE_BUTTON_TEXT "Обновление конфигурации"
#define LOCAL_TOOLS_TAB_CONTROL_DATE_BUTTON_TEXT "Установка даты и времени"
#define LOCAL_TOOLS_TAB_CONTROL_OFF_BUTTON_TEXT "Выключение и перезапуск"
#define LOCAL_TOOLS_TAB_CONTROL_LOG_BUTTON_TEXT "Управление журналом"
#define LOCAL_TOOLS_TAB_CONTROL_DETECTION_RESET_BUTTON_TEXT "Сброс сигналов"
#define LOCAL_TOOLS_TAB_CONTROL_JUSTIROVKA_BUTTON_TEXT "Юстировка"
#define LOCAL_TOOLS_TAB_CONTROL_POVOROTNIY_BUTTON_TEXT "ПР в дежурное положение"

#define LOCAL_TOOLS_LOG_CLEAR_LABEL_TEXT "Журнал очищен"
#define LOCAL_TOOLS_LOG_CLEAR_BUTTON_TEXT "Очистить журнал"
#define LOCAL_TOOLS_LOG_EXIT_BUTTON_TEXT "Выход"

#define LOCAL_TOOLS_DATE_ERROR_LABEL_TEXT "Ошибка ввода"
#define LOCAL_TOOLS_DATE_CLEAR_BUTTON_TEXT "Очистить"
#define LOCAL_TOOLS_DATE_EXIT_BUTTON_TEXT "Выход"

#define LOCAL_TOOLS_OFF_OFF_LABEL_TEXT "Питание можно выключить"
#define LOCAL_TOOLS_OFF_REBOOT_LABEL_TEXT "Выполняется перезапуск"
#define LOCAL_TOOLS_OFF_OFF_BUTTON_TEXT "Выключение"
#define LOCAL_TOOLS_OFF_REBOOT_BUTTON_TEXT "Перезапуск"
#define LOCAL_TOOLS_OFF_EXIT_BUTTON_TEXT "Выход"

#define LOCAL_TOOLS_OFF_MESSAGE_OFF_TEXT "Выключение"
#define LOCAL_TOOLS_OFF_MESSAGE_REBOOT_TEXT "Перезапуск"

#define LOCAL_TOOLS_UPDATE_EXIT_BUTTON_TEXT "Выход"
#define LOCAL_TOOLS_UPDATE_PC_BUTTON_TEXT "Загрузка конфигурации"
#define LOCAL_TOOLS_UPDATE_FR_BUTTON_TEXT "Обновление ПР"

#define LOCAL_TOOLS_UPDATE_PC_EXIT_BUTTON_TEXT "Выход"
#define LOCAL_TOOLS_UPDATE_PC_LOAD_DATA_TEXT   "Получение данных:     %"
#define LOCAL_TOOLS_UPDATE_PC_PROCESS_TEXT     "Обновление конфигурации"
#define LOCAL_TOOLS_UPDATE_PC_FINISH_TEXT      "Обновление конфигурации завершено успешно"
#define LOCAL_TOOLS_UPDATE_PC_ERROR_TEXT       "   Ошибка обновления   "
#define LOCAL_TOOLS_UPDATE_PC_MESSAGE_FINISH_TEXT "Конфигурация обновлена"

#define LOCAL_TOOLS_UPDATE_FR_EXIT_BUTTON_TEXT "Выход"
#define LOCAL_TOOLS_UPDATE_FR_LOAD_DATA_TEXT   "Передача данных:     %"
#define LOCAL_TOOLS_UPDATE_FR_PROCESS_TEXT     "Передача данных       "
#define LOCAL_TOOLS_UPDATE_FR_FINISH_TEXT      "    Передача данных завершена успешно    "
#define LOCAL_TOOLS_UPDATE_FR_ERROR_TEXT       "Ошибка передачи данных. ПР:     "
#define LOCAL_TOOLS_UPDATE_FR_MESSAGE_FINISH_TEXT "Данные траекторий загружены в ПР"

#define LOCAL_TOOLS_DATE_NEW_DATE_MESSAGE_TEXT "Установлены новые дата и время"

#define LOCAL_CONFIRMATION_USO_LOGIC_SEARCH_TEXT "Поступил сигнал о возгорании. Запускать поиск?"
#define LOCAL_CONFIRMATION_USO_LOGIC_COOLING_TEXT "Поступил сигнал о возгорании. Запускать орошение?"
#define LOCAL_CONFIRMATION_USO_LOGIC_GATE_TEXT "Поступил сигнал о возгорании. Открыть задвижки?"
#define LOCAL_CONFIRMATION_YES_BUTTON_TEXT "да"
#define LOCAL_CONFIRMATION_NO_BUTTON_TEXT "нет"

#define LOCAL_FINISH_FINISH_BUTTON_TEXT "Для завершения нажмите эту кнопку"
#define LOCAL_FINISH_FINISH_LABEL_TEXT "Завершение..."
#define LOCAL_FINISH_START_LABEL_TEXT "Запуск..."

#define LOCAL_LOGIC_COOLING_CANCEL_LOG_TEXT "Отмена старта орошения"
#define LOCAL_LOGIC_COOLING_START_LOG_TEXT "Старт орошения"
#define LOCAL_LOGIC_COOLING_FINISH_LOG_TEXT "Завершение орошения"
#define LOCAL_LOGIC_COOLING_LOG_FAULT_TEXT "Сбой программы орошения"

#define LOCAL_LOGIC_SEARCHING_CANCEL_LOG_TEXT "Отмена старта поиска очага"
#define LOCAL_LOGIC_SEARCHING_START_LOG_TEXT "Старт поиска очага"
#define LOCAL_LOGIC_SEARCHING_FINISH_LOG_TEXT "Завершение тушения"
#define LOCAL_LOGIC_SEARCHING_LOG_FAULT_TEXT "Сбой программы тушения"
#define LOCAL_LOGIC_SEARCHING_LOG_NOT_FIRE_DETECT_TEXT "Очаг возгорания не обнаружен"
#define LOCAL_LOGIC_SEARCHING_LOG_CANCEL_EXTINGUISHING_TEXT "Отмена тушения очага возгорания"
#define LOCAL_LOGIC_SEARCHING_LOG_START_EXTINGUISHING_TEXT "Старт тушения очага возгорания"
#define LOCAL_CONFIRMATION_USO_LOGIC_SEARCH_EXTINGUISHING_TEXT "Очаг возгорания найден. Запускать тушение?"

#define LOCAL_IOSYSTEM_MISSING_DEVICE_TEXT "Не найдено устройство расширения"
#define LOCAL_DETECTIONSYSTEM_MISSING_DEVICE_TEXT "Не найдено устройство расширения"
#define LOCAL_MONITORINGSYSTEM_MISSING_DEVICE_TEXT "Не найдено устройство расширения"
#define LOCAL_RPKSYSTEM_MISSING_DEVICE_TEXT "Не найдено устройство расширения"

#define LOCAL_TOOLS_JUSTIROVKA_ERROR_LABEL_TEXT      " Ошибка юстировки  "
#define LOCAL_TOOLS_JUSTIROVKA_SUCCESSFUL_LABEL_TEXT "Юстировка завершена"
#define LOCAL_TOOLS_JUSTIROVKA_ACTION_LABEL_TEXT     "   Выполнение...   "
#define LOCAL_TOOLS_JUSTIROVKA_CLEAR_BUTTON_TEXT     "Очистить"
#define LOCAL_TOOLS_JUSTIROVKA_EXIT_BUTTON_TEXT      "Выход"
#define LOCAL_TOOLS_JUSTIROVKA_ACTION_BUTTON_TEXT    "Старт"
#define LOCAL_TOOLS_JUSTIROVKA_LOG_MESSAGE_TEXT      "Выполнена юстировка"

#define LOCAL_MONITORING_DEVICE_SVAZ_S_PLATOY_PRIVODA_NET_TEXT "Отсутствует связь с модулем ПР      "
#define LOCAL_MONITORING_DEVICE_SVAZ_S_PLATOY_PRIVODA_EST_TEXT "Восстановление связи с модулем ПР   "
#define LOCAL_MESSAGE_TEXT_PONIZHENNOE_NAPRAZHENIE_NA_KONDENSATORAH "Пониженное напряжение источника питания"
#define LOCAL_MESSAGE_TEXT_NAPRAZHENIE_NA_KONDENSATORAH_V_NORME "Напряжение источника питания в норме"
#define LOCAL_MESSAGE_TEXT_NEISPRAVNOST_SILIVOGO_MOSTA "Неисправность силового моста"
#define LOCAL_MESSAGE_TEXT_VOSSTANOVLENIE_SILOVOGO_MOSTA "Восстановление силового моста"
#define LOCAL_MESSAGE_TEXT_NIZKOE_NAPRAZHENIE_PITANIA_CP "Низкое напряжение питания ЦП"
#define LOCAL_MESSAGE_TEXT_NAPRAZHENIE_PITANIA_CP_V_NORME "Напряжение питания ЦП в норме"
#define LOCAL_MESSAGE_TEXT_NIZKOE_NAPRAZHENIE_PITANIA_DRAIVERA "Низкое напряжение питания драйвера"
#define LOCAL_MESSAGE_TEXT_NIZKOE_NAPRAZHENIE_PITANIA_DRAIVERA_V_NORME "Напряжение питания драйв. в норме"
#define LOCAL_MESSAGE_TEXT_VISOKOE_NAPRAZHENIE_PITANIA_DRAIVERA "Высокое напряжение питания драйвера"
#define LOCAL_MESSAGE_TEXT_VISOKOE_NAPRAZHENIE_PITANIA_DRAIVERA_V_NORME "Напряжение питания драйв. в норме"
#define LOCAL_MESSAGE_TEXT_NIZKOE_NAPRAZHENIE_PITANIA_PLATI "Низкое напряжение питания платы"
#define LOCAL_MESSAGE_TEXT_NIZKOE_NAPRAZHENIE_PITANIA_PLATI_V_NORME "Напряжение питания платы в норме"
#define LOCAL_MESSAGE_TEXT_VISOKOE_NAPRAZHENIE_PITANIA_PLATI "Высокое напряжение питания платы"
#define LOCAL_MESSAGE_TEXT_VISOKOE_NAPRAZHENIE_PITANIA_PLATI_V_NORME "Напряжение питания платы в норме"
#define LOCAL_MESSAGE_TEXT_OSHIBKA_TESTA_FLESH_PAMATI "Ошибка теста флэш-памяти"
#define LOCAL_MESSAGE_TEXT_TEST_FLASH_PAMATI_VIPOLNEN_USPESHNO "Тест флэш-памяти выполнен успешно"
#define LOCAL_MESSAGE_TEXT_UROVNI_SIGNALOV_ENKODERA_NE_V_NORME "Неисправность энкодера"
#define LOCAL_MESSAGE_TEXT_UROVNI_SIGNALOV_ENKODERA_V_NORME "Энкодер в норме "
#define LOCAL_MESSAGE_TEXT_NEISPRAVNOST_KANALA_ENKODERA "Обрыв канала энкодера"
#define LOCAL_MESSAGE_TEXT_VOSSTANOVLENIE_KANALA_ENKODERA "Восстановление канала энкодера"
#define LOCAL_MESSAGE_TEXT_OSHIBKA_OPREDELENIA_NAPRAVLENIA "Ошибка определения направления"
#define LOCAL_MESSAGE_TEXT_VERNOE_OPREDELENIE_NAPRAVLENIA "Верное определение направления"
#define LOCAL_MESSAGE_TEXT_PRI_DVIZHENII_NE_MENAETSA_KOORDINATA "При движении не меняется координата"
#define LOCAL_MESSAGE_TEXT_PRI_DVIZHENII_MENAETSA_KOORDINATA "При движении меняется координата"
#define LOCAL_MESSAGE_TEXT_OTSUTSTVIE_TOKA_MOTORA "Отсутствие тока мотора"
#define LOCAL_MESSAGE_TEXT_TOK_MOTORA_V_PREDELAH_NORMI "Ток мотора в пределах нормы"
#define LOCAL_MESSAGE_TEXT_AVARIYNAYA_AMPLITUDE_TOKA_MOTORA "Аварийная амплитуда тока мотора "
#define LOCAL_MESSAGE_TEXT_AMPLITUDA_TOKA_MOTORA_V_NORME "Амплитуда тока мотора в норме"
#define LOCAL_MESSAGE_TEXT_NAPRAZHENIE_PITANIA_NIZHE_NORMI "Напряжение питания ниже нормы"
#define LOCAL_MESSAGE_TEXT_NAPRAZHENIE_PITANIA_NIZHE_NORMI_V_NORME "Напряжение питания в норме"
#define LOCAL_MESSAGE_TEXT_NAPRAZHENIE_PITANIA_VISHE_NORMI "Напряжение питания выше нормы"
#define LOCAL_MESSAGE_TEXT_NAPRAZHENIE_PITANIA_VISHE_NORMI_V_NORME "Напряжение питания в норме"
#define LOCAL_MESSAGE_TEXT_PR_OSHIBKA_TESTA_FLESH_PAMATI "Ошибка теста флэш-памяти"
#define LOCAL_MESSAGE_TEXT_PR_TEST_FLASH_PAMATI_VIPOLNEN_USPESHNO "Тест флэш-памяти выполнен успешно"
#define LOCAL_MESSAGE_TEXT_PR_NIZROE_NAPRAZHENIE_PITENIA_PROCESSORA "Низкое напряжение питания процессора"
#define LOCAL_MESSAGE_TEXT_PR_NIZROE_NAPRAZHENIE_PITENIA_PROCESSORA_V_NORME "Напряжение питания проц. в норме"
#define LOCAL_MESSAGE_TEXT_OBRIV_DATCHIKA_DAVLENIA "Обрыв датчика давления"
#define LOCAL_MESSAGE_TEXT_OBRIV_DATCHIKA_DAVLENIA_V_NORME "Датчик давления в норме"
#define LOCAL_MESSAGE_TEXT_KZ_DATCHIKA_DAVLENIA "КЗ датчика давления"
#define LOCAL_MESSAGE_TEXT_KZ_DATCHIKA_DAVLENIA_V_NORME "Датчик давления в норме"
#define LOCAL_MESSAGE_TEXT_PEREZAGRUZKA_CP "Перезапуск ЦП по причине зависания"
#define LOCAL_MESSAGE_TEXT_SVAZ_S_PR_VOSSTANOVLENA "Связь с ПР восстановлена"
#define LOCAL_MESSAGE_TEXT_OTSUTSTVUET_SVAZ_S_PR "Отсутствует связь с ПР"
#define LOCAL_MESSAGE_TEXT_OBRIV_MAGISTRALI_RPK "Обрыв магистрали управления РПК"
#define LOCAL_MESSAGE_TEXT_MAGISTRAL_RPK_VOSSTANOVLENA "Магистраль управления РПК восстановлена"
#define LOCAL_MESSAGE_TEXT_OTSUTSTVUET_SVAZ_S_SK "Отсутствует связь с СК"
#define LOCAL_MESSAGE_TEXT_SVAZ_S_SK_VOSSTANOVLENA "Связь с СК восстановлена"
#define LOCAL_MESSAGE_TEXT_OBRIV_SVAZI_S_ZATVOROM "Обрыв связи с затвором"
#define LOCAL_MESSAGE_TEXT_SVAZ_S_ZATVOROM_VOSSTANOVLENA "Связь с затвором восстановлена"
#define LOCAL_MESSAGE_TEXT_OBRIV_DATCHIKA_TEMPERATURI "Обрыв датчика температуры"
#define LOCAL_MESSAGE_TEXT_OBRIV_DATCHIKA_TEMPERATURI_ISPRAVEN "Датчик температуры исправен"
#define LOCAL_MESSAGE_TEXT_KZ_DATCHIKA_TEMPERATURI "КЗ датчика температуры"
#define LOCAL_MESSAGE_TEXT_KZ_DATCHIKA_TEMPERATURI_ISPRAVEN "Датчик температуры исправен"
#define LOCAL_MESSAGE_TEXT_OBRIV_DATCHIKA_VLAGNOSTI "Обрыв датчика влажности"
#define LOCAL_MESSAGE_TEXT_OBRIV_DATCHIKA_VLAGNOSTI_ISPRAVEN "Датчик влажности исправен"
#define LOCAL_MESSAGE_TEXT_KZ_KNOPOK_VNESHNEGO_POSTA "КЗ кнопок внешнего поста"
#define LOCAL_MESSAGE_TEXT_KZ_KNOPOK_VNESHNEGO_POSTA_VOSST "Связь с внешним постом восстановлена"
#define LOCAL_MESSAGE_TEXT_OBRIV_KNOPOK_VNESHNEGO_POSTA "Обрыв линии кнопок внешнего поста"
#define LOCAL_MESSAGE_TEXT_OBRIV_KNOPOK_VNESHNEGO_POSTA_VOSST "Связь с внешним постом восстановлена"
#define LOCAL_MESSAGE_TEXT_VOSSTANOVLENIE_SOEDINITELNIH_LINIY "Восстановление соединительных линий"
#define LOCAL_MESSAGE_TEXT_KZ_SOEDINITELNOY_LINII "КЗ соединительной линии"
#define LOCAL_MESSAGE_TEXT_OBRIV_SOEDINITELNOY_LINII "Обрыв соединительной линии"
#define LOCAL_MESSAGE_TEXT_OSHIBKA_OPREDELENIA_SOSTOYANIA_SL "Ошибка определения состояния СЛ"
#define LOCAL_MESSAGE_TEXT_SVAZ_VOSSTANOVLENA "Связь восстановлена"
#define LOCAL_MESSAGE_TEXT_OTSUTSTVUET_SVAZ "Отсутствует связь "
#define LOCAL_MESSAGE_TEXT_IZVECHATEL_V_NORME "Извещатель в норме"
#define LOCAL_MESSAGE_TEXT_NET_SVAZI_S_IZVECHATELEM "Нет связи с извещателем"
#define LOCAL_MESSAGE_TEXT_VNUTRENNAYA_OSHIBKA_IZVECHATELA "Внутренняя ошибка извещателя"
#define LOCAL_MESSAGE_TEXT_ZATVOR_OSHIBKA "Неисправность датчиков затвора"
#define LOCAL_MESSAGE_TEXT_ZATVOR_OTKRIT "Затвор открыт"
#define LOCAL_MESSAGE_TEXT_ZATVOR_ZAKRIT "Затвор закрыт"
#define LOCAL_MESSAGE_TEXT_TEMPERATURA_SHU_VISHE_NORMI "Температура ШУ выше нормы"
#define LOCAL_MESSAGE_TEXT_TEMPERATURA_SHU_VISHE_NORMI_V_NORME "Температура ШУ в пределах нормы"
#define LOCAL_MESSAGE_TEXT_TEMPERATURA_SHU_NIZHE_NORMI "Температура ШУ ниже нормы"
#define LOCAL_MESSAGE_TEXT_TEMPERATURA_SHU_NIZHE_NORMI_V_NORME "Температура ШУ в пределах нормы"
#define LOCAL_MESSAGE_TEXT_VISOKAJA_VLAZHNOST_VNUTRI_SHU "Высокая влажность внутри ШУ"
#define LOCAL_MESSAGE_TEXT_VISOKAJA_VLAZHNOST_VNUTRI_SHU_V_NORME "Влажность внутри ШУ в пределах нормы"
#define LOCAL_MESSAGE_TEXT_SREDNIY_TOK_MOTORA_VISHE_NORMI "Средний ток мотора выше нормы"
#define LOCAL_MESSAGE_TEXT_SREDNIY_TOK_MOTORA_VISHE_NORMI_V_NORME "Средний ток мотора в норме"
#define LOCAL_MESSAGE_TEXT_NEISPRAVNOST_DATCHIKA_TEMPERATURI_NA_PLATE "Неисправность датчика темп. на плате"
#define LOCAL_MESSAGE_TEXT_NEISPRAVNOST_DATCHIKA_TEMPERATURI_NA_PLATE_V_NORME "Датчик температуры на плате в норме"
#define LOCAL_MESSAGE_TEXT_NEISPRAVNOST_DATCHIKA_TEMPERATURI_PRIVODA "Неисправность датчика темп. привода"
#define LOCAL_MESSAGE_TEXT_NEISPRAVNOST_DATCHIKA_TEMPERATURI_PRIVODA_V_NORME "Датчик температуры привода в норме"
#define LOCAL_MESSAGE_TEXT_PEREZAPUSK_CP "Перезапуск ЦП по причине зависания"
#define LOCAL_MESSAGE_TEXT_ZATVOR_NEISPRAVNOST "Время работы затвора превышено"
#define LOCAL_MESSAGE_TEXT_PR_DAVLENIE_EST "ОТВ подано"
#define LOCAL_MESSAGE_TEXT_PR_DAVLENIE_NET "Подача ОТВ прекращена"
#define LOCAL_MESSAGE_TEXT_VOSSTANOVLENIE_DATCHIKOV_ZATVORA "Восстановление датчиков затвора"
#define LOCAL_MESSAGE_TEXT_ZATVOR_V_NORME "Время работы затвора в норме"
#define LOCAL_MESSAGE_TEXT_START_SEARCH "Старт поиска очага"
#define LOCAL_MESSAGE_TEXT_START_OROSHENIA "Старт орошения"
#define LOCAL_MESSAGE_TEXT_STOP_POISKA_OROSHENIA "Стоп поиска/орошения"

#define LOCAL_MESSAGE_TEXT_INITIALIZATION "Инициализация"

#define LOCAL_MESSAGE_TEXT_SIGNAL_O_VOZGORANII ""
#define LOCAL_MESSAGE_TEXT_OTMENA_SIGNALA_O_VOZGORANII ""

#define LOCAL_MESSAGE_TEXT_PEREGORELA_LAMPA "Перегорела лампа сканера"
#define LOCAL_MESSAGE_TEXT_KZ_V_CEPI_LAMPI "Короткое замыкание в цепи лампы сканера"
#define LOCAL_MESSAGE_TEXT_OTKAZ_POZICIONIROVANIJA "Отказ при позиционировании сканера"
#define LOCAL_MESSAGE_TEXT_OTKAZ_OTKRITIJA "Отказ при открытии сканера"
#define LOCAL_MESSAGE_TEXT_TEMPERATURA_V_NORME "Температура сканера в норме"
#define LOCAL_MESSAGE_TEXT_TEMPERATURA_NIZHE_NORMI "Температура сканера ниже нормы"
#define LOCAL_MESSAGE_TEXT_TEMPERATURA_VISHE_NORMI "Температура сканера выше нормы"

#define LOCAL_MESSAGE_TEXT_PENABAK_PERELIV "Перелив пенообразователя"
#define LOCAL_MESSAGE_TEXT_PENABAK_NORMA "Уровень пенообразователя в норме"
#define LOCAL_MESSAGE_TEXT_PENABAK_UTECHKA "Утечка пенообразователя"
#define LOCAL_MESSAGE_TEXT_PENABAK_50_IZRASHODOVANO "Половина пенообразователя израсходовано"
#define LOCAL_MESSAGE_TEXT_PENABAK_NAPOLOVINU_ZAPOLNEN "Бак наполовину заполнен"
#define LOCAL_MESSAGE_TEXT_PENABAK_MIN_UROVEN "Минимальный уровень пенообразователя"
#define LOCAL_MESSAGE_TEXT_PENABAK_DATCHIK_NEISPRAVEN "Датчик уровня КУП неисправен"
#define LOCAL_MESSAGE_TEXT_PENABAK_DATCHIK_ISPRAVEN "Датчик уровня КУП исправен"
#define LOCAL_MESSAGE_TEXT_PENABAK_SVAZ_OFF "Отсутствует связь с КУП"
#define LOCAL_MESSAGE_TEXT_PENABAK_SVAZ_ON "Связь с КУП восстановлена"

#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_OFF_BK "Потеря связи с платой расш. БК16"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_ON_BK "Восст. связи с платой расш. БК16"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_OFF_RPK "Потеря связи с платой расш. РПК"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_ON_RPK "Восст. связи с платой расш. РПК"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_OFF_MONITORING "Потеря связи с платой расш. Мониторинг"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_ON_MONITORING "Восст. связи с платой расш. Мониторинг"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_OFF_FV300 "Потеря связи с платой расш. FV300"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_ON_FV300 "Восст. связи с платой расш. FV300"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_OFF_TV "Потеря связи с платой расш. TV"
#define LOCAL_MESSAGE_TEXT_EXT_SVAZ_ON_TV "Восст. связи с платой расш. TV"

#endif

#ifdef LOCAL_ENG

#define LOCAL_LOG_CONTROL_UP_BUTTON_NAME "Up"
#define LOCAL_LOG_CONTROL_DOWN_BUTTON_NAME "Down"
#define LOCAL_LOG_CONTROL_LAST_BUTTON_NAME "Last"

#define LOCAL_USO_MODE_CONTROL_MODE_FULL_AUTO_TEXT "FullAuto"
#define LOCAL_USO_MODE_CONTROL_MODE_HALF_AUTO_TEXT "HalfAuto"
#define LOCAL_USO_MODE_CONTROL_MODE_TOOLS_TEXT "Tools"
#define LOCAL_USO_MODE_CONTROL_USO_MODE_SET_MESSAGE_FULL_AUTO "Full auto mode"
#define LOCAL_USO_MODE_CONTROL_USO_MODE_SET_MESSAGE_HALF_AUTO "Half auto mode"
#define LOCAL_USO_MODE_CONTROL_USO_MODE_SET_MESSAGE_TOOLS "Tools mode"

#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER "defaultProcessorInterruptHandler"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER0 "defaultProcessorInterruptHandler0"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER1 "defaultProcessorInterruptHandler1"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER2 "defaultProcessorInterruptHandler2"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER3 "defaultProcessorInterruptHandler3"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER4 "defaultProcessorInterruptHandler4"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER5 "defaultProcessorInterruptHandler5"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER6 "defaultProcessorInterruptHandler6"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER7 "defaultProcessorInterruptHandler7"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER8 "defaultProcessorInterruptHandler8"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER9 "defaultProcessorInterruptHandler9"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER10 "defaultProcessorInterruptHandler10"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER11 "defaultProcessorInterruptHandler11"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER12 "defaultProcessorInterruptHandler12"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER13 "defaultProcessorInterruptHandler13"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER14 "defaultProcessorInterruptHandler14"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER15 "defaultProcessorInterruptHandler15"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER16 "defaultProcessorInterruptHandler16"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER17 "defaultProcessorInterruptHandler17"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER18 "defaultProcessorInterruptHandler18"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER19 "defaultProcessorInterruptHandler19"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER20 "defaultProcessorInterruptHandler20"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER21 "defaultProcessorInterruptHandler21"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER22 "defaultProcessorInterruptHandler22"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER23 "defaultProcessorInterruptHandler23"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER24 "defaultProcessorInterruptHandler24"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER25 "defaultProcessorInterruptHandler25"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER26 "defaultProcessorInterruptHandler26"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER27 "defaultProcessorInterruptHandler27"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER28 "defaultProcessorInterruptHandler28"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER29 "defaultProcessorInterruptHandler29"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER30 "defaultProcessorInterruptHandler30"
#define LOCAL_INTERRUPT_DEFAULT_PROCESSOR_INTERRUPT_HANDLER31 "defaultProcessorInterruptHandler31"

#define LOCAL_LOG_LOG_CREATE_MESSAGE "Created new log"

#define LOCAL_TOOLS_TAB_CONTROL_EXIT_BUTTON_TEXT "Exit"
#define LOCAL_TOOLS_TAB_CONTROL_UPDATE_BUTTON_TEXT "Config"
#define LOCAL_TOOLS_TAB_CONTROL_DATE_BUTTON_TEXT "Date time"
#define LOCAL_TOOLS_TAB_CONTROL_OFF_BUTTON_TEXT "Off"
#define LOCAL_TOOLS_TAB_CONTROL_LOG_BUTTON_TEXT "Log"
#define LOCAL_TOOLS_TAB_CONTROL_POVOROTNIY_BUTTON_TEXT "Svernut PR"

#define LOCAL_TOOLS_LOG_CLEAR_LABEL_TEXT "Clear"
#define LOCAL_TOOLS_LOG_CLEAR_BUTTON_TEXT "Clear"
#define LOCAL_TOOLS_LOG_EXIT_BUTTON_TEXT "Exit"

#define LOCAL_TOOLS_DATE_ERROR_LABEL_TEXT "Error"
#define LOCAL_TOOLS_DATE_CLEAR_BUTTON_TEXT "Clear"
#define LOCAL_TOOLS_DATE_EXIT_BUTTON_TEXT "Exit"

#define LOCAL_TOOLS_OFF_OFF_LABEL_TEXT "Power can be switched off"
#define LOCAL_TOOLS_OFF_REBOOT_LABEL_TEXT "Restarts"
#define LOCAL_TOOLS_OFF_OFF_BUTTON_TEXT "Poweroff"
#define LOCAL_TOOLS_OFF_REBOOT_BUTTON_TEXT "Restart"
#define LOCAL_TOOLS_OFF_EXIT_BUTTON_TEXT "Exit"

#define LOCAL_TOOLS_OFF_MESSAGE_OFF_TEXT "Poweroff"
#define LOCAL_TOOLS_OFF_MESSAGE_REBOOT_TEXT "Reboot"

#define LOCAL_TOOLS_UPDATE_EXIT_BUTTON_TEXT "Exit"
#define LOCAL_TOOLS_UPDATE_PC_BUTTON_TEXT "Load"
#define LOCAL_TOOLS_UPDATE_FR_BUTTON_TEXT "Update FR"

#define LOCAL_TOOLS_UPDATE_PC_EXIT_BUTTON_TEXT "Exit"
#define LOCAL_TOOLS_UPDATE_PC_LOAD_DATA_TEXT "Load data:     %"
#define LOCAL_TOOLS_UPDATE_PC_PROCESS_TEXT   "Update          "
#define LOCAL_TOOLS_UPDATE_PC_FINISH_TEXT    "Update+         "
#define LOCAL_TOOLS_UPDATE_PC_ERROR_TEXT     "Error:          "
#define LOCAL_TOOLS_UPDATE_PC_MESSAGE_FINISH_TEXT "Config update"

#define LOCAL_TOOLS_DATE_NEW_DATE_MESSAGE_TEXT "New date and time"

#endif

